# Generated by Django 4.2.1 on 2023-05-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('phone', 'Phone'), ('tablet', 'Tablet'), ('laptop', 'Laptop'), ('television', 'Television')], max_length=10)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
            ],
        ),
    ]
